title: Meet New Creators
author: Sandra Girgis
email: shgirgis@ebnetorg
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
FaceBook_username: Sandra Hany # DO NOT include the @ character, or else the build will fail!
Snapchat_username: sandra_girgis26 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
